import { Link } from "react-router-dom";
import { Mail, MapPin, Phone } from "lucide-react";
import { useLanguage } from "@/i18n/LanguageContext";

export const Footer = () => {
  const { t } = useLanguage();
  const groups = [[t("footer.services"), [[t("footer.aiSeo"), "/services/ai-search-optimization"], [t("footer.technicalSeo"), "/services/technical-seo"], [t("footer.localSeo"), "/services/local-seo"]]], [t("footer.company"), [[t("footer.aboutUs"), "/about"], [t("footer.caseStudies"), "/case-studies"], [t("nav.pricing"), "/pricing"]]], [t("footer.resources"), [[t("footer.freeTools"), "/tools"], [t("footer.blog"), "/blog"], [t("nav.audit"), "/audit"]]]] as const;
  return <footer className="border-t border-paper/20 bg-void text-paper"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-14 sm:px-8 md:grid-cols-[1.3fr_repeat(3,1fr)] lg:px-12"><div><p dir="ltr" className="font-heading text-4xl uppercase [unicode-bidi:isolate]">ConstantSEO<span className="text-lime">.</span></p><p className="mt-4 max-w-xs text-sm leading-relaxed text-paper">{t("footer.taglineShort")}</p><p className="mt-7 text-xs font-bold uppercase tracking-[0.14em] text-lime">{t("footer.tagline")}</p></div>{groups.map(([title, links]) => <div key={title}><h2 className="text-xs font-bold uppercase tracking-[0.16em] text-paper">{title}</h2><ul className="mt-5 space-y-3">{links.map(([label, href]) => <li key={href}><Link to={href} className="text-sm hover:text-lime">{label}</Link></li>)}</ul></div>)}<div className="md:col-span-4"><div className="flex flex-wrap gap-x-6 gap-y-3 border-y border-paper/20 py-5 text-sm text-paper"><a href="mailto:akhmad@constantlabs.ai" dir="ltr" className="inline-flex items-center gap-2 [unicode-bidi:isolate] hover:text-lime"><Mail className="h-4 w-4" />akhmad@constantlabs.ai</a><a href="tel:+971561495656" dir="ltr" className="inline-flex items-center gap-2 [unicode-bidi:isolate] hover:text-lime"><Phone className="h-4 w-4" />+971 56 149 5656</a><span className="inline-flex items-center gap-2"><MapPin className="h-4 w-4" />{t("footer.location")}</span></div><div className="mt-5 flex flex-wrap justify-between gap-4 text-xs text-paper"><span>{t("footer.copyright")}</span><span className="flex gap-4"><Link to="/privacy">{t("footer.privacy")}</Link><Link to="/terms">{t("footer.terms")}</Link></span></div></div></div></footer>;
};
