import { useEffect, useState } from "react";
import { Link, useLocation } from "react-router-dom";
import { Menu, X } from "lucide-react";
import { useLanguage } from "@/i18n/LanguageContext";

export const Navbar = () => {
  const { t, toggleLang, isAr } = useLanguage();
  const [scrolled, setScrolled] = useState(false);
  const [mobileOpen, setMobileOpen] = useState(false);
  const location = useLocation();
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 12); window.addEventListener("scroll", onScroll, { passive: true }); return () => window.removeEventListener("scroll", onScroll); }, []);
  const links = [{ label: t("nav.services"), href: "/services" }, { label: t("nav.tools"), href: "/tools" }, { label: t("nav.pricing"), href: "/pricing" }, { label: t("nav.about"), href: "/about" }];
  const color = scrolled ? "text-ink" : "text-paper";
  return <header className={`fixed inset-x-0 top-0 z-40 border-b transition-colors ${scrolled ? "border-line bg-paper/95 shadow-sm backdrop-blur" : "border-paper/15 bg-void/70 backdrop-blur"}`}><nav aria-label={t("home.nav.label")} className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 sm:h-20 sm:px-8 lg:px-12"><Link to="/" className={`font-heading text-2xl uppercase tracking-tight ${color}`}>ConstantSEO<span className="text-lime">.</span></Link><div className="hidden items-center gap-1 md:flex">{links.map(({ label, href }) => <Link key={href} to={href} className={`px-3 py-2 text-xs font-bold uppercase tracking-[0.1em] transition-colors ${location.pathname === href ? "text-evidence-blue" : `${color} hover:text-lime`}`}>{label}</Link>)}</div><div className="flex items-center gap-2"><button type="button" onClick={toggleLang} className={`border px-3 py-2 text-xs font-bold uppercase tracking-[0.1em] transition-colors ${scrolled ? "border-line text-ink hover:bg-ink hover:text-paper" : "border-paper/40 text-paper hover:bg-paper hover:text-ink"}`} aria-label={isAr ? "Switch to English" : "التبديل إلى العربية"}>{isAr ? "EN" : "عربي"}</button><Link to="/audit" className="hidden bg-lime px-4 py-2 text-xs font-bold uppercase tracking-[0.1em] text-ink transition-transform hover:-translate-y-0.5 sm:inline-flex">{t("nav.audit")}</Link><button type="button" aria-expanded={mobileOpen} aria-controls="mobile-navigation" onClick={() => setMobileOpen((value) => !value)} className={`grid h-9 w-9 place-items-center border md:hidden ${scrolled ? "border-line text-ink" : "border-paper/40 text-paper"}`}><span className="sr-only">{mobileOpen ? t("home.nav.close") : t("home.nav.open")}</span>{mobileOpen ? <X className="h-4 w-4" /> : <Menu className="h-4 w-4" />}</button></div></nav>{mobileOpen && <div id="mobile-navigation" className={`border-t px-5 py-4 md:hidden ${scrolled ? "border-line bg-paper" : "border-paper/15 bg-void"}`}>{links.map(({ label, href }) => <Link key={href} to={href} onClick={() => setMobileOpen(false)} className={`block border-b py-3 text-sm font-bold uppercase tracking-[0.1em] ${scrolled ? "border-line text-ink" : "border-paper/20 text-paper"}`}>{label}</Link>)}<Link to="/audit" onClick={() => setMobileOpen(false)} className="mt-4 block bg-lime px-4 py-3 text-center text-xs font-bold uppercase tracking-[0.1em] text-ink">{t("nav.audit")}</Link></div>}</header>;
};
