import { useState } from "react";
import { Calendar, MessageCircle } from "lucide-react";
import { useLanguage } from "@/i18n/LanguageContext";
import { DisplayTitle, Eyebrow, SectionShell } from "@/components/marketing/primitives";

export const ZCalBookingSection = () => {
  const { t } = useLanguage();
  const [showCalendar, setShowCalendar] = useState(false);
  return <SectionShell className="border-y border-line bg-paper text-ink"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[0.9fr_1.1fr] lg:items-center"><div><Eyebrow>{t("home.booking.eyebrow")}</Eyebrow><DisplayTitle className="mt-4">{t("home.booking.title")}</DisplayTitle><p className="mt-5 max-w-lg text-lg leading-relaxed text-ink/70">{t("zcal.subtitle")}</p></div><div className="border border-line bg-ink p-6 text-paper sm:p-8">{showCalendar ? <><iframe src="https://zcal.co/i/v5bi9xYQ?embed" className="h-[760px] w-full border-0 bg-paper" title="Book a consultation" /><button type="button" onClick={() => setShowCalendar(false)} className="mt-4 text-sm text-paper/60 hover:text-lime">← {t("zcal.back")}</button></> : <><Calendar className="h-8 w-8 text-lime" /><h3 className="mt-12 font-heading text-4xl uppercase leading-none">{t("home.booking.panelTitle")}</h3><p className="mt-4 max-w-md text-sm leading-relaxed text-paper/65">{t("home.booking.panelCopy")}</p><div className="mt-8 flex flex-wrap gap-3"><button type="button" onClick={() => setShowCalendar(true)} className="inline-flex items-center gap-2 bg-lime px-5 py-3 text-sm font-bold uppercase tracking-[0.08em] text-ink hover:bg-lime/85">{t("zcal.bookNow")}</button><a href="https://wa.me/971561495656" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 border border-paper/35 px-5 py-3 text-sm font-bold uppercase tracking-[0.08em] text-paper hover:border-lime hover:text-lime"><MessageCircle className="h-4 w-4" />{t("zcal.whatsapp")}</a></div><p className="mt-8 text-xs font-bold uppercase tracking-[0.1em] text-paper/50">{t("zcal.note")}</p></>}</div></div></SectionShell>;
};
